name: Misskey Bot JS Cron
concurrency:
  group: bot-group
  cancel-in-progress: true # 新しいのが来たら古い方を殺す
on:
  schedule:
  - cron: '7,17,27,37,47,57 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # キャッシュエラーを避けるため、一旦キャッシュ設定はなしでいきます

      - name: Install dependencies
        run: |
          npm install misskey-js@latest @google/generative-ai@latest

      - name: Run bot
        env:
          MK_DOMAIN: ${{ secrets.MK_DOMAIN }}
          MK_TOKEN: ${{ secrets.MK_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: node bot.js
